### ISSUE TITLE
Change the AccountAge to a proper date

### ISSUE THREAD

**Issue by sirjahames** [bloxit-devs/blox-it#2]
![image](https://user-images.githubusercontent.com/75079031/216867353-ff928937-9777-45a0-9194-120156ba83e9.png)

Change the integer count to a properly formatted date that is the difference between the creation date and `Date.now()`.
Currently, just having the days seems like a UX issue and it doesn't even state its unit (days, hours). It could show `1 Year, 40 Days, 23 Seconds`. Even though hovering over the Creation Date shows this, it would be better than just a plain integer.

Just a small change to improve user experience.

**Comment by AnthonyFuller** [comment]
When making the command, I decided to keep it a number have it like the data Roblox uses when calling account age in games.
